### ISSUE TITLE
 Floating point exception in DFT GW-BSE with phenanthrene

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#279] opened 2019-09-04 12:54 UTC
**XTP branch**: electrostatics

**Cmake compilation** 
```
prefix=$HOME/local
cmake -H. -Bbuild  -DBUILD_XTP=ON -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_CXX_FLAGS=-pg ..
cmake --build build --target install -- -j8
```

**Command**
```
xtp_tools -e dftgwbse -t 1 -o /tmp/xtp_2019-09-04T13:06:11.063467/OPTIONFILES/dftgwbse.xml > dftgwbse.log
```
**Error**
```
Floating point exception
```

**dftgwbse.log** (last lines)
```
... ... 2019-9-4 14:14:7 DFT data was created by xtp
... ... 2019-9-4 14:14:7 Loaded DFT Basis Set ubecppol
... ... 2019-9-4 14:14:7 Filled DFT Basis of size 374
... ... 2019-9-4 14:14:7 Loaded Auxbasis Set aux-ubecppol
... ... 2019-9-4 14:14:7 Filled Auxbasis of size 1682
... ... 2019-9-4 14:14:8 Calculating Mmn_beta (3-center-repulsion x orbitals)
```
**gdb report**:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `xtp_tools -e dftgwbse -t 1 -o /tmp/xtp_2019-09-04T13:06:11.063467/OPTIONFILES/d'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007f3e52d1c2b3 in void Eigen::internal::evaluateProductBlockingSizesHeuristic<double, double, 1, long>(long&, long&, long&, long) ()
   from /home/felipe/local/lib/libvotca_xtp.so.6
[Current thread is 1 (Thread 0x7f3e5374dd00 (LWP 32160))]
```

**gwbse.xml**
```xml
<gwbse>
        <basisset help="basiset to use">ubecppol</basisset>
        <auxbasisset help="auxilliary basiset to use">aux-ubecppol</auxbasisset>
        <ranges help="default: all levels in RPA, 1:2*HOMO in QP and BSE; other options: factor,explicit">default</ranges>
        <rpamax help="only needed, if ranges is factor or explicit, number of levels in rpa"></rpamax>
        <qpmin help="only needed, if ranges is factor or explicit, lowest MO to be used in GW"></qpmin>
        <qpmax help="only needed, if ranges is factor or explicit, highest MO to be used in GW"></qpmax>
        <bsemin  help="only needed, if ranges is factor or explicit, lowest MO to be used in BSE"></bsemin>
        <bsemax help="only needed, if ranges is factor or explicit, highest MO to be used in BSE"></bsemax>
        <vxc  help="Exchange correlation functional computation for GW">
                <functional help="functional name(s) according to LIBXC">XC_HYB_GGA_XC_PBEH</functional>
                <grid help="grid quality xcoarse,coarse,medium,fine,xfine">medium</grid>
        </vxc>
        <scissor_shift help="preshift unoccupied MOs by a constant for GW calculation" unit="hartree">0.2</scissor_shift>
        <mode help="use single short (G0W0) or self-consistent GW (evGW)">evGW</mode>
        <tasks help="tasks to do gw,singlets,triplets or all">gw,singlets,triplets</tasks>
        <exctotal help="maximum number of BSE states to calculate">25</exctotal>

        <eigensolver help="options for BSE eigenvalue decompostion">
                <dodavidson help="use davidson solver" >1</dodavidson>
                <davidson_correction help="DPR or OHLSEN" >DPR</davidson_correction>
                <davidson_tolerance help="loose,normal,strict"> normal</davidson_tolerance>
                <davidson_ortho help="orthogonalisation routine GS or QR" >GS</davidson_ortho>
                <davidson_update help=" how large the search space can become min, safe, max" >safe</davidson_update>
                <davidson_maxiter help="max iterations" >50</davidson_maxiter>
                <domatrixfree help="solve without explicitly setting up BSE matrix, (slower but a lot less memory required" >0</domatrixfree>
        </eigensolver>
</gwbse>
```

**dftgwbse.xml**
```xml
<options>
<dftgwbse help="Electronic Excitations using GW-BSE">

        <dftpackage help="Package for DFT ground state">/tmp/xtp_2019-09-04T13:06:11.063467/OPTIONFILES/xtpdft.xml</dftpackage>

        <mode help="Calculator mode: energy or optimize">energy</mode>
        <reporting help="Package for DFT ground state">noisy</reporting>
        <archive help=".orb file to create">system.orb</archive>
        <molecule help="Input geometry .xyz">/tmp/xtp_2019-09-04T13:06:11.063467/phenanthrene.xyz</molecule>

        <gwbse_engine>
            <tasks help="guess,input,dft,parse,gwbse">input,dft,parse,gwbse</tasks>
            <dftlog help="qmpackage log file to parse">system_dft.orb</dftlog>
            <mofile help="qmpackage file with MO coefficients">system.gbw</mofile>
            <gwbse_options help="xml file with gwbse options">/tmp/xtp_2019-09-04T13:06:11.063467/OPTIONFILES/gwbse.xml</gwbse_options>
            <redirect_logger help="">0</redirect_logger>
        </gwbse_engine>

        <geometry_optimization help="geometry optimization options">
            <state help="initial state to optimize for">s1</state>
            <filter help="tries to identify state without looking at the energy">
                <oscillator_strength>0.001</oscillator_strength>
            </filter>
            <convergence help="Convergence criteria for geometry optimization">
                    <energy help="default: 1.e-6 Hartree">0.01</energy>
                    <RMSForce help="default: 3.e-5 Hartree/Bohr">0.01</RMSForce>
                    <MaxForce help="default: 1.e-4 Hartree/Bohr">0.01</MaxForce>
                    <RMSStep help="default: 6.e-4 Bohr">0.01</RMSStep>
                    <MaxStep help="default: 1.e-3 Bohr">0.01</MaxStep>
            </convergence>

            <optimizer help="optimiser method">
                <method>BFGS-TRM</method>
                <method>BFGS-TRM</method>
                <trust help="initial trustregion in Angstrom">0.01</trust>
            </optimizer>
            <forces>
                <method help="finite differences method, central or forward">central</method>
                <CoMforce_removal help="Remove total force on molecule">1</CoMforce_removal>
                <displacement help="default: 0.001 Angstrom">0.01</displacement>
            </forces>
        </geometry_optimization>
</dftgwbse>
</options>
```
**xtpdft.xml**
```xml
<package>
<spin help="multiplicity of qm configuration">1</spin>
<name help="name of dft package">xtp</name>
<charge help="charge of system">0</charge>
<convergence>
    <energy help="DeltaE at which calculation is converged" unit="hartree">1e-7</energy>
    <method help="Main method to use for convergence accelertation DIIS or mixing">DIIS</method>
    <DIIS_start help="DIIS error at which DIIS takes over">0.002</DIIS_start>
    <ADIIS_start help="DIIS error at which ADIIS takes over">0.8</ADIIS_start>
    <DIIS_length help="old hamiltonians to keep in history">20</DIIS_length>
    <levelshift help="levelshift to apply to hamiltonian " unit="hartree">0.0</levelshift>
    <levelshift_end help="DIIS error at levelshifting is disabled">0.2</levelshift_end>
</convergence>
<initial_guess help="Method to use to make initial guess, independent(electrons) or atom(densities)">atom</initial_guess>
<basisset help="basiset to use">ubecppol</basisset>
<ecp help="Pseudo potential to use, Delete if you do not want to use ecps">ecp</ecp>
<auxbasisset help="auxiliary to use, Delete if you do not want to use RI approximation">aux-ubecppol</auxbasisset>  
<integration_grid help="grid quality xcoarse,coarse,medium,fine,xfine">medium</integration_grid>
<integration_grid_small help="use a smaller grid for start of calculation">0</integration_grid_small>
<xc_functional help="functional name(s) according to LIBXC">XC_HYB_GGA_XC_PBEH</xc_functional>
<max_iterations help="max iterations to use">200</max_iterations>
<read_guess help="try to read guess from orbitals file">0</read_guess>
<cleanup help="files to delete identified by fileending"></cleanup>
</package>
```

**Molecular Coordinates**
```
24

C      4.2671    4.2111    6.0319
C      3.4011    3.3615    5.3683
C      3.4337    3.2256    3.9602
C      5.2115    4.9687    5.3136
C      5.2684    4.8584    3.9386
C      4.3927    3.9962    3.2378
C      4.4609    3.8894    1.8079
C      2.5375    2.3405    3.2259
C      2.6439    2.2686    1.8051
C      1.5565    1.5396    3.8570
C      3.6253    3.0639    1.1234
C      1.7801    1.4135    1.0811
C      0.8327    0.6443    1.7266
C      0.7230    0.7108    3.1284
H      4.2174    4.2934    7.1143
H      2.6847    2.7914    5.9497
H      5.8899    5.6345    5.8399
H      5.9930    5.4369    3.3702
H      5.2011    4.4876    1.2821
H      1.4474    1.5684    4.9358
H      3.6849    2.9903    0.0402
H      1.8767    1.3730   -0.0014
H      0.1752   -0.0084    1.1590
H     -0.0207    0.1078    3.6424
```

**Comment by JensWehner** [comment] 2019-09-04 14:16
What do you mean with your cmake commands?

**Comment by JensWehner** [comment] 2019-09-04 14:18
What kind of architecture?

**Comment by JensWehner** [comment] 2019-09-04 14:19
did all tests run correctly?

**Comment by JensWehner** [comment] 2019-09-04 14:21
did the dft finish correctly? Please give the whole log file

**Comment by JensWehner** [comment] 2019-09-04 14:22
Btw. you can also attach files instead of pasting them.

**Comment by felipeZ** [comment] 2019-09-04 14:39
> What do you mean with your cmake commands? Bbuild etc??

Instead of doing `mkdir build && cd build` you can do `cmake -H. -Bbuild` Also the cmake command `cmake --build build` calls make for you

**Comment by felipeZ** [comment] 2019-09-04 14:46
> did the dft finish correctly? Please give the whole log file

[dftgwbse.log](https://github.com/votca/xtp/files/3575043/dftgwbse.log)

**Comment by felipeZ** [comment] 2019-09-04 14:47
> Btw. you can also attach files instead of pasting them.

Yes, but I am running in the `gpumuscet` and I was lazy ;)

**Comment by felipeZ** [comment] 2019-09-04 14:49
> did all tests run correctly?

Yes, they finished normally.
```
100% tests passed, 0 tests failed out of 151

Label Time Summary:
csg            =   9.80 sec*proc (64 tests)
ctp            =   0.21 sec*proc (5 tests)
integration    =   0.02 sec*proc (1 test)
regression     =   0.00 sec*proc (1 test)
tools          =   4.03 sec*proc (74 tests)
unit           =   0.57 sec*proc (27 tests)
votca          =  17.78 sec*proc (150 tests)
xtp            =   7.59 sec*proc (63 tests)

Total Test time (real) =  17.85 sec
```

**Comment by JensWehner** [comment] 2019-09-04 22:07
the problem is the failure of the dft run

**Comment by JensWehner** [comment] 2019-09-09 16:32
fixed in https://github.com/votca/xtp/commit/e404e5886c010e8eb5ac035540c3b17867997db8

**Closed by JensWehner** 2019-09-09 16:32 UTC
Labels: bug
