### ISSUE TITLE
 gbw files are not copied into the right folder.

### ISSUE THREAD

**Issue by gtirimbo** [votca/xtp#472] opened 2020-06-17 15:27 UTC
In iqm the gbw files generated with eqm are not copied in the right folders. I spot the problem in the following section
https://github.com/votca/xtp/blob/0c5dd843715f3b0d48faf04d7fd43e07f21c540c/src/libxtp/jobcalculators/iqm.cc#L329

**Comment by JensWehner** [comment] 2020-06-17 17:03
in which folders are they copied and which folder should they be copied to?

**Comment by gtirimbo** [comment] 2020-06-17 17:23
three folders are created in OR_FILES : molecules, workdir_eqm and workdir_iqm.
-molecules contains the .orb files (no subfolders)
-workdir_eqm contains the .gbw (for each frame one subfolder for each molecule)
-workdir_iqm is the target folder in which to copy. 
There is also the problem that is looking for the .gbw files with the wrong name
I solved in this way: For instance at line 332 I put this
 `std::string mol_dir_A = (format("%1%%2%%3%") % "molecule" % "_" % ID_A).str();
          std::string gbwFileA =
              (arg_pathA / eqm_work_dir / "workdir_eqm" / frame_dir / mol_dir_A / "system.gbw").generic_string();`

Don't know if this solution is general or it is just an hack working in my case.

**Comment by JensWehner** [comment] 2020-06-17 18:10
is this related to the `-name` option that was introduced? What wrong name are they looking for?

**Comment by JensWehner** [comment] 2020-06-17 18:48
Can you submit a PR for this?

**Comment by baumeier** [comment] 2020-06-17 18:48
I think the problem is not in `iqm` but in `eqm` when `orca` is used.

**Comment by baumeier** [comment] 2020-06-17 18:52
When we are constructing the merged guess, we rely on orca's `orca_mergefragment` tool to take two `*.gbw` files and merge them. 
For that, it is not sufficient to store the parsed DFT data into the HDF5 orb file and store them in `OR_FILES/molecules/frame_0/molecule_X.orb` but also to copy the `OR_FILES/workdir_eqm/frame_0/molecule_X/system.gbw` to `OR_FILES/molecules/frame_0/molecule_X.gbw` because this is where `iqm` is looking for it.

**Closed** 2020-06-20 08:58 UTC
