### ISSUE TITLE
_state_index and overlap

### ISSUE THREAD

**Issue by mbarbry** [votca/xtp#146] opened 2018-08-06 10:09 UTC
In the routine `Iterate` of `qmmachine.cc`, there is an issue with the vector `_state_index`.
This vector will have a size different than 1 only if the option `overlap` is set to True. 
However, at the end of _do_gwbse, the routine tries to access to different part of the vector `_state_index`.  For example, 

    _state_index[_state - 1  - orb_iter_input.getGWAmin()]

and `_state - 1  - orb_iter_input.getGWAmin()` seems to get values different than 0 even if the option `overlap` is set to False. And I get some segfault since its try to access to not allocated part of the vector. I guess that the index should be set to 0 if the option `overlap` is set to False.

**Comment by baumeier** [comment] 2018-08-06 11:07
> This vector will have a size different than 1 only if the option overlap is set to True.

I don't think this is the case. There is also the oscillator strength filter (line 481) and the charge transfer filter (line 493). 

However, the latter two are only used for exciton GW-BSE/MM, while the overlap filter currently only applies to quasiparticle GW/MM. And the latter only for the polarizable version of GW/MM from the second iteration onward. If _state is the HOMO level index (counted from 1...), this should be ok. Of course, if the filter is used in a different context, or _state <= 0, things are obviously out of bound.

**Comment by mbarbry** [comment] 2018-08-06 12:38
Then it is probably something incorrect in my inputs (see attached file), I'm going quite blindly with the parameters for the moment.
Nevertheless, some checking about arrays can not warm I believe. At least to avoid some segfaults that are difficult to catch.

[inpqmmm.tar.gz](https://github.com/votca/xtp/files/2262534/inpqmmm.tar.gz)

**Comment by baumeier** [comment] 2018-08-06 13:34
`        <filter>
          <oscillator_strength>1.0</oscillator_strength>
          <charge_transfer>1.0</charge_transfer>
        </filter>`

The problem is that the two filters you are requesting are exciton filters. Since you don't calculate excitons, that state_index vector will indeed not be set. 

Please note that GW/MM for quasiparticles only is something that is still being developed. At the moment, one should only use that functionality with the overlap filter, so that even for a "static" GW/MM, the correct energy can be reported.

Maybe something like this should be made default for GW/MM, if no other filter is active:
` for (unsigned _i = 0; _i < orb_iter_input.QPdiagEnergies().size(); _i++) {
                                _state_index.push_back(_i);
                            }`

But indeed, there should be additional checks, what do you think @JensWehner ?

**Comment by mbarbry** [comment] 2018-08-06 14:03
Removing the parameters `oscillator_strength` and `charge_transfer` from qmmm.xml, I still get a segfault ...

**Comment by baumeier** [comment] 2018-08-06 14:06
Did you add <overlap> instead?

**Comment by baumeier** [comment] 2018-08-06 14:32
That way it still happens what you described initially. The vector is of length 1, and when an energy is to be reported, one runs out of bounds.

Can you check if it still segfaults after adding the overlap tags in between the filters arguments?

Bottom line: there should be a default for GW/MM.

**Comment by mbarbry** [comment] 2018-08-06 15:07
ja seems to work now.
Thanks!

**Comment by JensWehner** [comment] 2018-09-13 08:31
closed by #152

**Closed by JensWehner** 2018-09-13 08:31 UTC
